# Default values for silverkey.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

openresty:
  image: "openresty/openresty"
  tag: "latest"
  pullPolicy: "IfNotPresent"

etcd:
  image: "elcolio/etcd"
  tag: "latest"

service:
  type: ClusterIP
  port: 80



