apiVersion: v1
kind: Service
metadata:
  name: {{ template "silverkey.fullname" . }}-openresty
  labels:
    app: {{ template "silverkey.name" . }}-openresty
    chart: {{ template "silverkey.chart" . }}-openresty
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "silverkey.name" . }}-openresty
    release: {{ .Release.Name }}
